version: "3.9"

services:
  app:
    build: "."
    container_name: strawberry-app
    restart: always
    command: poetry run uvicorn main:app --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: strawberry-postgres
    restart: always
    environment:
      POSTGRES_DB: strawberry
      POSTGRES_PASSWORD: strawberry
      POSTGRES_USER: strawberry
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
